name: Deploy
on:
  push:
    branches:
      - none

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@main

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: cloud-57
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: GCP Authentication
        run: |
          gcloud auth configure-docker us.gcr.io
          gcloud container clusters get-credentials default-cluster --zone us-central1-a

      - name: Build
        run: |        
          docker pull us.gcr.io/cloud-57/fiftysevenmedia-api:build || true
          docker pull us.gcr.io/cloud-57/fiftysevenmedia-api:latest || true
          docker build \
            --target build \
            --cache-from us.gcr.io/cloud-57/fiftysevenmedia-api:build \
            -t us.gcr.io/cloud-57/fiftysevenmedia-api:build \
            -f .devops/Dockerfile .
          docker build \
            --cache-from us.gcr.io/cloud-57/fiftysevenmedia-api:build \
            --cache-from us.gcr.io/cloud-57/fiftysevenmedia-api:latest \
            -t us.gcr.io/cloud-57/fiftysevenmedia-api:${GITHUB_SHA} \
            -t us.gcr.io/cloud-57/fiftysevenmedia-api:latest \
            -f .devops/Dockerfile .
          docker push us.gcr.io/cloud-57/fiftysevenmedia-api

      - name: Setup Helm
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs.git
          helm repo add cloud-57 gs://cloud-57-helm
          helm repo update

      - name: Rollout Deploy
        run: |
          helm upgrade --install fiftysevenmedia cloud-57/cloud-57 \
          -f .devops/helm/values.yaml \
          --version v1.0.2 \
          --set image.repository=us.gcr.io/cloud-57/fiftysevenmedia-api \
          --set image.tag=${GITHUB_SHA} \
          -n backend
          kubectl rollout status --watch deployment fiftysevenmedia -n backend

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@master

      - name: Cache Node Modules
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - run: npm install
      
      - name: Build
        run: npm run build -- --environment=production

      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: frontend