name: Deploy
on:
  push:
    branches:
      - master

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@master

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: gcloud auth configure-docker us.gcr.io

      - name: Build
        run: |        
          docker build \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg GUARDIAN_SECRET=${{ secrets.GUARDIAN_SECRET }} \
            --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
            --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            -f deploy/Dockerfile \
            -t us.gcr.io/cloud-57/fiftysevenmedia-api:latest .
      - name: Publish
        run: docker push us.gcr.io/cloud-57/fiftysevenmedia-api:latest

      - name: Start rolling update
        run: |
          gcloud compute instance-groups managed rolling-action replace fiftysevenmedia-api \
            --region=us-central1 \
            --max-unavailable 0 \
            --max-surge 4

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@master

      - name: Cache Node Modules
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - run: npm install
      
      - name: Build
        run: npm run build -- --environment=production

      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: frontend